# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - scanbandz-qr-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://scanbandz.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b58d6751ac1549ebb33736f226b14b28 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d378de394b654510b12e0c058f008bcd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: scanbandz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b58d6751ac1549ebb33736f226b14b28 }}/qr_code_server:${{ github.sha }}
        file: ./Dockerfile
        platforms: linux/arm64

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'scanbandz-qr-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_22686c60ecbd4f078991b5882f7b645a }}
        images: 'scanbandz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b58d6751ac1549ebb33736f226b14b28 }}/qr_code_server:${{ github.sha }}'